### ISSUE TITLE
Better slack notification in Github release workflow

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/k#2530]
See https://runtimeverification.slack.com/archives/C7E701MFG/p1648665369029709

Basically, we want to use the official slack api github action to provide a more fine-tuned reporting of workflow failures on slack that is less verbose.

**Comment by radumereuta** [comment]
What we want is:
- new messages
- when merge to master fails

**Comment by radumereuta** [comment]
Duplicate of: https://github.com/runtimeverification/k/issues/2623

**Comment by F-WRunTime** [comment]
@dwightguth @radumereuta 
I have written [an example notification we can use that triggers based off another workflows success or failure](https://github.com/runtimeverification/devops-actions/blob/master/.github/workflows/TrackAndNotifySlack.yaml). This can then plug a message into a slack channel or direct to an individual. 

Alternatively we could also add this to the [K release.yaml](https://github.com/runtimeverification/k/blob/master/.github/workflows/release.yml#L216) at the end, as as secondary job. The job determines if success or failure occurred previously. [Example here](https://github.com/runtimeverification/devops-actions/blob/master/.github/workflows/EventTriggering.yaml#L80)

In the case specifically for K. We can use a separate workflow like to notify release of K failed and provide a link in the message. 
```yaml
---
name: Action PASS/FAIL Tracking
on:
  workflow_run: 
    workflows: [ Release ]
    types:
      - completed

jobs: 
  on-success:
    runs-on: [self-hosted, Linux]
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    container: dockerhub-runtimeverification.com:5000/base/build-image:1
    env:
      GH_TOKEN: ${{ secrets.ORG_PAT }}
    steps:
      - name: collect-info
        run: |
          echo "Use Context Info from Failed Run Triggering"
      - uses: slackapi/slack-github-action@v1.22.0
        id: slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "pass_fail": "PASSED",
              "link_to_result": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
  on-failure:
    runs-on: [self-hosted, Linux]
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    env:
      GH_TOKEN: ${{ secrets.ORG_PAT }}
    steps:
      - name: collect-info
        run: |
          echo "Use Context Info from Failed Run Triggering"
      - uses: slackapi/slack-github-action@v1.22.0
        id: slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "pass_fail": "FAILED",
              "link_to_result": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
```
