### ISSUE TITLE
Support YAML syntax for outer parsing

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#4177]
Currently we use XML, which we consistently get negative feedback at conferences about because it feels legacy and can be hard to read. XML is good because it has very clear open/close brackets for each cell.

YAML also has the nice property of being easily outer-parsed, but does not feel legacy and is much less verbose than XML. Indentation of YAML allows you to write arbitrary code directly into each YAML block. We can use an off-the-shelf YAML parser for doing configuration parsing, then check that the schema is allowed by the declared configuration after the fact and then just parse the contents of the cells themselves directly.

This would also line up better with how we display information to the user in Simbolik, because essentially a YAML like display is produced there for them to inspect, and then we have to explain how that maps to the XML like syntax anyway.

Overall, offering YAML as a way to write rule syntax I think could make parsing much faster (inner parsing only needs to be done on individual cells, not entire configurations), and would make definitions more compact and readable, nad be less scary to users.

**Comment by ehildenb** [comment]
Pinging @RaoulSchaffranek .

**Comment by RaoulSchaffranek** [comment]
I strongly support the YAML-based outer parser. YAML's conciseness compared to XML reduces the emphasis on the outer syntax, allowing a greater focus on the inner syntax. This also means we can display more content on the screen without the need to scroll. Also, YAML's popularity means that a lot of tooling is available for it, including syntax highlighters.

While the syntax for configurations seems relatively straightforward, I'm curious about how we should handle rules. For instance, what would be the YAML counterpart for the rule `<k> #pushCallStack => .K ... </k>`?

**Comment by ehildenb** [comment]
A rule like that would be:

```
k: #pushCallStack => .K ...
```

A question in my mind is do we only support YAML syntax for configurations, or also for definitions in general? I think just for configurations would be nice:

```
module MY-MODULE
  imports FOO

  configuration
    k: $PGM:Pgm
    statusCode: .Status
    cell:
      subcell: ...
      othersubcell: ...

  syntax Bar ::= bar ( Int ) [function]

  rule
    k: I:Int ~> #push => . ...
    subcell: 0 => bar(0)
    requires baz(I)
```

The question I have is what to do about:

- Cell collections?
- Cell attributes?
- Rewrites of entire subconfigurations?

**Comment by tothtamas28** [comment]
According to the YAML specification, mapping are unordered (https://yaml.org/spec/1.2.2/#mapping), so if we want to have this syntax for cells:

```yaml
k: $PGM:Pgm
statusCode: .Status
cell:
  subcell: ...
  othersubcell: ...
```

then we need a parser that guarantees that the order of entries is preserved.

**Edit**: YAML also has "Ordered Mappings":

```yaml
--- !!omap
- k: $PGM:Pgm
- statusCode: .Status
```

**Comment by tothtamas28** [comment]
> Cell collections?

YAML supports "Sequence of Mappings" (https://yaml.org/spec/1.2.2/#21-collections):

```yaml
account:
  - acctID: 0
    balance: 0
  - acctID: 1
    balance: 100
```

**Comment by tothtamas28** [comment]
> Cell attributes?

There is no direct equivalent of an XML attribute in YAML, so we'll probably have to model them as key-value pairs:

```yaml
configuration:
  accounts:
    multiplicity: *
    type: Map
    account:
      acctID: 0
      balance: 0      
```

**Comment by tothtamas28** [comment]
> Rewrites of entire subconfigurations?

We need a symbol to represent rewrites, something that is not a valid cell name. Maybe

```yaml
'=>':
   - k: foo
   - k: .K
```

although it's a bit noisy (but still only four characters).
